version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - .yarn-cache
            - node_modules

      - run:
          name: Build
          command: yarn build

      - run:
          name: Publish npm package
          command: |
            if [ ! -z ${npm_TOKEN+x} ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${npm_TOKEN}" > ~/project/.npmrc
              npm version prerelease --preid=${CIRCLE_BUILD_NUM}.${CIRCLE_BRANCH}.`git rev-parse --short HEAD` --no-git-tag-version
              npm publish --tag next
            fi

      - run:
          name: Danger JS
          command: |
            if [ ! -z $DANGER_GITHUB_API_TOKEN ]; then
              yarn danger ci
            else
              echo No token set, skipping
            fi
