version: 2
general:
  tags:
    ignore:
      /ci-skip.*/s
workflows:
  version: 2
  build:
    jobs:
      -build
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - .yarn-cache
            - node_modules

      - run:
          name: Build
          command: yarn build

      - run:
          name: Push stats
          command: |
            statsFile=stats/generated

            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "Not a pull request, skipping step"
              exit 0
            fi
            cp stats/current stats/generated
            if [ -z "$(git status --porcelain stats/generated)" ]; then
              echo "$statsFile has not changed, exiting"
              exit 0
            fi

            echo "Going to push updated $statsFile"
            git config user.email "miroslav.stastny+dusty@gmail.com"
            git config user.name "DustyTheBot"
            git add $statsFile
            git commit -m "update $statsFile"
            git push --set-upstream origin ${CIRCLE_BRANCH}

      - run:
          name: Publish npm package
          command: |
            if [ ! -z ${npm_TOKEN+x} ] && [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${npm_TOKEN}" > ~/project/.npmrc
              npm version prerelease --preid=${CIRCLE_BUILD_NUM}.${CIRCLE_BRANCH}.`git rev-parse --short HEAD` --no-git-tag-version
              npm publish --tag next
            fi
